name: Docker Image CI

on:
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
      runs-on: ubuntu-latest
      permissions: write-all
  
      steps:
      - uses: actions/checkout@v4
  
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: running
        run: |
          echo ${{ github.actor }}
          echo ${{ github.repository_owner  }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Hinata/Dockerfile
          push: true
          tags: ak2083/hinata:latest
